//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class GioiThieu
    {
        public int ID { get; set; }
        public Nullable<int> IdCLB { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public string LichSuHinhThanh { get; set; }
        [ForeignKey("IdCLB")]
        public virtual CLB CLB { get; set; }
    }
}
