//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieu
    {
        public int ID { get; set; }
        public Nullable<int> IdCLB { get; set; }
        public string MoTa { get; set; }
        public byte[] HinhAnh { get; set; }
        public string LichSuHinhThanh { get; set; }
    
        public virtual CLB CLB { get; set; }
    }
}
