//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Poster
    {
        public Poster()
        {
            HinhAnh = "~/Areas/Admin/Resource/HinhAnh/addImg.jpg";
            
        }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        public int ID { get; set; }
        public string TenPoster { get; set; }
        public string HinhAnh { get; set; }
        public bool Status { get; set; }
    }
}
