//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLDSHoatDong
    {
        public int ID { get; set; }
        public string ChuDe { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> IdCLB { get; set; }
        public Nullable<int> IdLoaiHD { get; set; }
    
        public virtual CLB CLB { get; set; }
        public virtual LoaiHD LoaiHD { get; set; }
    }
}
