//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public int ID { get; set; }
        public string TieuDeSK { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string NoiDung { get; set; }
        public string KetQua { get; set; }
        public string DiaDiem { get; set; }
        public string HinhThuc { get; set; }
        public Nullable<int> IdLoaiSK { get; set; }
        public Nullable<int> IdCLB { get; set; }
    
        public virtual CLB CLB { get; set; }
        public virtual LoaiSuKien LoaiSuKien { get; set; }
    }
}
