//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTNhatKy
    {
        public int ID { get; set; }
        public Nullable<int> IdThanhVien { get; set; }
        public Nullable<System.DateTime> TGThamGia { get; set; }
        public Nullable<int> SKDaThamGia { get; set; }
    
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
